accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm,  PwdResetForm,  PwdResetConfirmForm, PwdChangeForm

app_name = 'accounts'

urlpatterns = [
     path('login/', auth_views.LoginView.as_view(template_name="registration/login.html",
                                                authentication_form=UserLoginForm), name='login'),

    path('profile/',views.profile, name='profile'),
    path('profile/edit',views.edit, name='edit'),
    path('profile/delete/',views.delete_user, name='deleteuser'),
    path('register/', views.accounts_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>)/', views.activate, name='activate'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="registration/password_reset_form.html", form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name = 'registration/password_reset_confirm.html', form_class=PwdResetConfirmForm), name="pwdresetconfirm"),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name = "registration/password_change_form.html", form_class=PwdChangeForm), name='pwdforgot'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='homepage'),
    path('search/', views.post_search, name='post_search'),
    path('<slug:post>/', views.post_single, name='post_single'),
    path('category/<category>/', views.CatListView.as_view(), name='category'),
]

fuzzy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'fuzzy'

urlpatterns = [
    path('userfuzzy/', views.fuzzy_extractor, name='fuzzy'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

print(settings.MEDIA_URL)

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('account/', include('django.contrib.auth.urls')),
    path('fuzzy/', include('fuzzy.urls', namespace='fuzzy')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey


def user_directory_path(instance, filename):
    return 'posts/%Y/%m/%d/'.format(instance.id, filename)


class Category(models.Model):
    name = models.CharField(max_length=100)


    # return the title of the post. 
    # if you don't do this, it will be post(1), post(2)...
    def __str__(self):
        return self.name


class Post(models.Model):

    
    # not only post all object but also published
    class NewManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset() .filter(status='published')

    options = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, default=1)# create ForeighKey for Category table. 
    #'on_delete': In here we already took a connection between Post and Category. If now we delete a category which doesn't exist, then the database will be broken. 
    # Therefore, this function defines what we should do the post if we delete a category.
    # 'default=1': the post that we've already made they're going to be assigned to default which is going to be the ccategory default.

    title = models.CharField(max_length=250)
    excerpt = models.TextField(null=True)
    image = models.ImageField(
        upload_to=user_directory_path, default='posts/default2.jpg')
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    publish = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    content = models.TextField()
    status = models.CharField(max_length=10, choices=options, default='draft')
    objects = models.Manager()  # default manager
    newmanager = NewManager()  # custom manager, call the class # to bring the filter out the posts that are published, we're never going to return posts that aren't published.

    
    # to get the blog title so that can get the slug information
    def get_absolute_url(self):
        return reverse('blog:post_single', args=[self.slug])

    
    # define the ordering of that list or the list of post.
    # post的排序由時間由newest-->oldest
    class Meta:
        ordering = ('-publish',)

    
    # return the title of the post. 
    # if you don't do this, it will be post(1), post(2)...
    def __str__(self):
        return self.title


class Comment(MPTTModel):

    # evertyime we create new comment there's going to be an association between that comment and an item in the post table.
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    
    # others parameters
    name = models.CharField(max_length=50)
    parent = TreeForeignKey('self', on_delete=models.CASCADE,
                            null=True, blank=True, related_name='children')
    email = models.EmailField()
    content = models.TextField()
    publish = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)  # if you want to delete the comment, you could change the status from true to false.(true -> comments live; false -> comments won't e shown)

    class MPTTMeta:
        order_insertion_by = ['publish']


    # return the comment of the post by the author name. 
    def __str__(self):
        return self.name

fuzzy/forms.py
from django import forms


class FuzzyExtractorForm(forms.Form):
    old_password = forms.CharField(
        label='field 1', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3 col-sm-12', 'placeholder': 'Old Password', 'id': 'form-oldpass'}))


class FuzzyExtractorReproduceForm(forms.Form):
    helper = forms.CharField(
        label='field 2', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3 col-sm-12', 'placeholder': 'Old Password', 'id': 'form-oldpass1111'}))

fuzzy/views.py
import sys

from django.contrib.auth.decorators import login_required
# Create your views here.
from django.http import JsonResponse
from django.shortcuts import render

from .forms import FuzzyExtractorForm, FuzzyExtractorReproduceForm
from .fuzzy_extractor import FuzzyExtractor

extractor = FuzzyExtractor(16, 8)
helperList = []


@login_required(login_url='/account/login/')
def fuzzy_extractor(request):
    if request.method == 'POST' and request.POST.get('old_password'):
        form = FuzzyExtractorForm(request.POST)
        if form.is_valid():
            # process form data and update the database
            key, helper = extractor.generate('AABBCCDDEEFFGGHH')
            helperList.append(helper)
            data = {'field1': str(key), 'field2': str(helper)}
        return JsonResponse(data)
    elif request.method == 'POST' and request.POST.get('helper'):
        form = FuzzyExtractorReproduceForm(request.POST)
        if form.is_valid():
            r_key = extractor.reproduce('AABBCCDDEEFFGGHH', helperList[-1])
            data = {'field1': str(r_key)}
        return JsonResponse(data)
    else:
        form = FuzzyExtractorForm()
        reProduceFornm = FuzzyExtractorReproduceForm()
        context = {'form': form, 'reProduceFornm': reProduceFornm}
        return render(request, 'temp.html', context)

fuzzy/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <title> 強韌雙因子生物辨識模組開發 Welcome to blog </title>

</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">強韌雙因子生物辨識模組開發</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:profile' %}">My Profile</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/search">Search</a>
        </li>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for category in category_list %}
            <a class="dropdown-item" href="/category/{{ category.name}}">
              {{ category.name|title }}
            </a>
            {% endfor %}
          </div>
          
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0" action="/search/" method="get">
        <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search" required>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
  {% block content %}
  {% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
  </script>
</body>

</html>

fuzzy/templates/temp.html
{% extends "base.html" %}

{% load static %}


{% block title %}
Welcome to Blog
{% endblock %}
{% block content %}

<p class="col-sm-12">
    <div id="myDIV" style="display:block;" class="col-sm-12">
      </div>

      <div class="col-sm-12">
        <form id="my-form" class="col-sm-12" >
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary my-2">Submit</button>
        </form>
      </div>

      <div id="result" class="col-sm-12">
        <div class="form-floating mb-3 form-floating-height lg-3 col-sm-12">
          <textarea id="fuzzyKey" class="form-control" placeholder="" id="floatingTextarea2Disabled" style="height: 300px" disabled></textarea>
          <label for="floatingTextarea2Disabled">Comments</label>
        </div>
      </div>

       {% comment %} <p>{{category_list}}</p> {% endcomment %}
      <div id="result" class="col-sm-12">
        <form id="reProduceFornm" class="col-sm-12">
          {% csrf_token %}
          {{ reProduceFornm.as_p }}
          <button type="submit" class="btn btn-primary my-2">Submit</button>
        </form>
      </div>

      <div id="result" class="col-sm-12">
        <div class="form-floating mb-3 form-floating-height lg-3 col-sm-12">
          <textarea id="reProduceKey" class="form-control col-sm-12" placeholder="" id="floatingTextarea2Disabled" style="height: 300px" disabled></textarea>
          <label for="floatingTextarea2Disabled col-sm-12">Comments</label>
        </div>
      </div>
</p>

<script>
  const form = document.getElementById('my-form');
  const reProduceFornm = document.getElementById('reProduceFornm')
  const result = document.getElementById('result');
  const fuzzyOutput = document.getElementById('fuzzyKey')
  const helper = document.getElementById('form-oldpass1111')
  console.log(helper)
  const reProduceOutput = document.getElementById('reProduceKey')
  form.addEventListener('submit', (event) => {
    event.preventDefault();
    const formData = new FormData(form);
    
    fetch('{% url "fuzzy:fuzzy" %}', {
      method: 'POST',
      body: formData
    })
    .then(response => response.json())
    .then(data => {
      console.log(fuzzyOutput)
      fuzzyOutput.placeholder = data.field1
      helper.value = data.field2
      {% comment %} result.innerHTML = `
        <p>Updated content:</p>
        <div class="form-floating mb-3 form-floating-height lg-3 col-sm-12">
          <textarea class="form-control col-sm-12" placeholder="${data.field1}" id="floatingTextarea2Disabled" style="height: 300px" disabled></textarea>
          <label for="floatingTextarea2Disabled">Comments</label>
        </div>
        <ul class="col-sm-12">
          <li>Field 1: ${data.field1}</li>
          <li>Field 2: ${data.field2}</li>
        </ul>
      `; {% endcomment %}
    });
  });
  reProduceFornm.addEventListener('submit', (event) => {
    event.preventDefault();
    const formData = new FormData(reProduceFornm);
    
    fetch('{% url "fuzzy:fuzzy" %}', {
      method: 'POST',
      body: formData
    })
    .then(response => response.json())
    .then(data => {
      console.log(fuzzyOutput)
      reProduceOutput.placeholder = data.field1
    });
  });
</script>
{% include "base/footer.html" %}
{% endblock %}